#!/usr/bin/env python3
"""Generate the public command catalog from the operational registry."""

import argparse
import json
from pathlib import Path
import tomllib


ROOT = Path(__file__).resolve().parents[1]


def render() -> str:
    with (ROOT / "config/commands.toml").open("rb") as stream:
        commands = tomllib.load(stream)["commands"]
    catalog = []
    for command in commands:
        if not command.get("phrases"):
            continue
        capability = command.get("capability", "")
        category = (
            "apps" if capability.startswith("folder.") else
            "audio" if capability.startswith("audio.") else
            "windows" if capability.startswith(("window.", "workspace.", "visual.")) or command["action"] == "clarify" else
            "readout" if command["id"] in {"read_clipboard", "stop_speaking"} else
            "system"
        )
        operation = capability or command["action"]
        details = command.get("payload", command.get("argv", command.get("targets")))
        catalog.append({
            "id": command["id"], "category": category,
            "phrases": command["phrases"], "action": command["action"],
            "argv": operation + (" " + json.dumps(details) if details else ""),
            "reply": command.get("prompt", command.get("reply", "")),
            "description": command["id"].replace("_", " ").capitalize() + ".",
        })
    return "// Generated by tools/build-site-catalog.py; do not edit.\nconst ARCHI_COMMANDS = " + json.dumps(catalog, indent=2) + ";\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "site/js/commands.js"
    content = render()
    if args.check:
        if not path.exists() or path.read_text() != content:
            print("Site catalog is stale; run python tools/build-site-catalog.py")
            return 1
    else:
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
